// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demo.proto

package demo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Response struct {
	Result               *Result  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type Result struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{2}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Result) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "demo.Request")
	proto.RegisterType((*Response)(nil), "demo.Response")
	proto.RegisterType((*Result)(nil), "demo.Result")
}

func init() { proto.RegisterFile("demo.proto", fileDescriptor_ca53982754088a9d) }

var fileDescriptor_ca53982754088a9d = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8f, 0x5d, 0xaa, 0xc2, 0x40,
	0x0c, 0x85, 0x6f, 0xaf, 0xb5, 0xd5, 0xf8, 0x83, 0xe4, 0xa9, 0x08, 0x82, 0x0c, 0x3e, 0x88, 0x0f,
	0x45, 0xea, 0x16, 0x5c, 0x41, 0x70, 0x03, 0xd5, 0x06, 0x11, 0x9c, 0xa6, 0x36, 0xd3, 0xfd, 0x4b,
	0x53, 0xf5, 0xed, 0xe3, 0xcc, 0xf0, 0x9d, 0x13, 0x80, 0x8a, 0xbd, 0xe4, 0x4d, 0x2b, 0x41, 0x30,
	0xee, 0xd9, 0x6d, 0x20, 0x25, 0x7e, 0x75, 0xac, 0x01, 0x11, 0xe2, 0xba, 0xf4, 0x9c, 0x45, 0xdb,
	0x68, 0x3f, 0x25, 0x63, 0x77, 0x84, 0x09, 0xb1, 0x36, 0x52, 0x2b, 0xe3, 0x0e, 0x92, 0x96, 0xb5,
	0x7b, 0x06, 0xfb, 0x31, 0x2b, 0xe6, 0xb9, 0xd9, 0xc8, 0x32, 0xfa, 0xbc, 0xb9, 0x1c, 0x92, 0x21,
	0xe9, 0x7d, 0x37, 0xa9, 0x06, 0xdf, 0x98, 0x8c, 0x71, 0x05, 0x23, 0xaf, 0xf7, 0xec, 0xdf, 0x2a,
	0x7a, 0x2c, 0x0a, 0x88, 0xcf, 0xec, 0x05, 0x0f, 0x90, 0x5e, 0x58, 0x43, 0xd9, 0x3c, 0x70, 0xf1,
	0x15, 0xdb, 0xae, 0xf5, 0xf2, 0xd7, 0x63, 0x3b, 0xdc, 0xdf, 0x35, 0xb1, 0x0b, 0x4e, 0xef, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x94, 0xb7, 0x05, 0xc5, 0xcf, 0x00, 0x00, 0x00,
}
